server:
  port: 9200

spring:
  application:
    name: rabbit-mq

  # rabbitmq 配置
  rabbitmq:
    addresses: localhost:5676,localhost:5678,localhost:5680
    username: root
    password: 123456
    publisher-returns: true
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 50
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
