server:
  port: 7001

spring:
  application:
    name: eureka-gateway-01
#  security:
#    user:
#      name: root
#      password: password

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9999/eureka/
    register-with-eureka: false


# 转发机制
zuul:
  routes:
    # 自定义网关的名称，用于区分代理。
    consumer:
      path: /consumer/**
      serviceId: eureka-client-01
  host:
    connect-timeout-millis: 10000
    max-total-connections: 10000
    max-per-route-connections: 10000
  # 忽略除了上述path地址之外的配置路由
  ignored-services: '*'
