server:
  port: 7001

spring:
  application:
    name: eureka-consumer-01
  security:
    user:
      name: root
      password: password

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9999/eureka/
    register-with-eureka: false


# 在feign里启动hystrix（熔断器） Feign将使用断路器包装所有方法
feign:
  hystrix:
    enabled: true


# 转发机制
zuul:
  routes:
    # 自定义网关的名称，用于区分代理。
    comsumer:
      path: /zuulTest/**
      serviceId: http://localhost:7001/zuul/
#    consumer1:
#      path: /user/**
#      serviceId: http://localhost/user/
  host:
    connect-timeout-millis: 10000
    max-total-connections: 10000
    max-per-route-connections: 10000
  # 忽略除了上述path地址之外的配置路由
  ignored-services: '*'
