server:
  port: 8002

spring:
  application:
    name: eureka-client-01
#  security:
#    user:
#      name: root
#      password: password
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
    username: root
    password: qwe@ASD123

eureka:
  instance:
    # 过期最大等待时间 到了之后会将服务剔除
    lease-expiration-duration-in-seconds: 90
    # 心跳检测间隔
    lease-renewal-interval-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
    # 是否允许获取注册中心的注册表信息
    fetch-registry: true
    # Eureka Client 上缓存的服务注册信息，定期更新的时间间隔，默认 30 秒
    registry-fetch-interval-seconds: 30
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9999/eureka/

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: false

logging:
  level:
    com.example.client1.feign.ClientService: debug