
server:
  port: 8002

spring:
  application:
    name: eureka-client-01
#  security:
#    user:
#      name: root
#      password: password
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.211.80.218:3306/chat?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Wwangyong@202007

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9999/eureka/
