
server:
  port: 8002

spring:
  application:
    name: eureka-client-01
  security:
    user:
      name: root
      password: password
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://locahost:3306/kec?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&transformedBitIsBoolean=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9999/eureka/
